---
name: bosh

releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=236
    sha1: 88dd60313dbd7dd832faa44c90493ffa6cd85448
  - name: bosh-google-cpi
    url: http://storage.googleapis.com/bosh-stemcells/bosh-google-cpi-5.tgz
    sha1: c5de3053f233e6ef42c2a4228fa94179d955cc84

resource_pools:
  - name: vms
    network: private
    stemcell:
      url: https://storage.googleapis.com/bosh-stemcells/light-bosh-stemcell-3153-google-kvm-ubuntu-trusty-go_agent.tgz
      sha1: 7f0e4da9507edb122a25fcc1c17bf1d46651842c
    cloud_properties:
      machine_type: n1-standard-1
      root_disk_size_gb: 40
      root_disk_type: pd-standard

disk_pools:
  - name: disks
    disk_size: 32_768
    cloud_properties:
      type: pd-standard

networks:
  - name: private
    type: dynamic
    cloud_properties:
      network_name: default
      tags:
        - bosh

  - name: public
    type: vip

jobs:
  - name: bosh
    instances: 1

    templates:
      - name: nats
        release: bosh
      - name: redis
        release: bosh
      - name: postgres
        release: bosh
      - name: powerdns
        release: bosh
      - name: blobstore
        release: bosh
      - name: director
        release: bosh
      - name: health_monitor
        release: bosh
      - name: cpi
        release: bosh-google-cpi
      - name: registry
        release: bosh-google-cpi

    resource_pool: vms
    persistent_disk_pool: disks

    networks:
      - name: private
        default:
          - dns
          - gateway
      - name: public
        static_ips:
          - 146.148.74.81 # <--- Replace with the static IP

    properties:
      nats:
        address: 127.0.0.1
        user: nats
        password: nats-password

      redis:
        listen_address: 127.0.0.1
        address: 127.0.0.1
        password: redis-password

      postgres: &db
        listen_address: 127.0.0.1
        host: 127.0.0.1
        user: postgres
        password: postgres-password
        database: bosh
        adapter: postgres

      dns:
        address: 146.148.74.81 # <--- Replace with the static IP
        domain_name: microbosh
        db: *db
        recursor: 8.8.8.8

      blobstore:
        address: 146.148.74.81 # <--- Replace with the static IP
        port: 25250
        provider: dav
        director:
          user: director
          password: director-password
        agent:
          user: agent
          password: agent-password

      director:
        address: 127.0.0.1
        name: micro-google
        db: *db
        cpi_job: cpi
        user_management:
          provider: local
          local:
            users:
              - name: admin
                password: yiM4Citph1oT4Lak5me
              - name: hm
                password: ecS1iT1Fov5Ka2gRas1
      hm:
        director_account:
          user: hm
          password: ecS1iT1Fov5Ka2gRas1
        resurrector_enabled: true

      ntp: &ntp
        - 169.254.169.254

      google: &google_properties
        project: data-compass
        json_key:  '{
                      "type": "service_account",
                      "project_id": "data-compass",
                      "private_key_id": "34e09f91621e2e4f45c2b780ae84ca8c5362119a",
                      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCeJed74PNUI6w7\ng0FX0mniFqv8PJdLnn+b58I39BEotTUTYq2xpCyr2i5kZlhSeSl2PZi854R/l563\ny4PwJDF3hrjW3tV/E1/nauJrbbPXNrYGWzSfRDbK0f7tblsQCEZZ2hrSsBcAYIK3\n74hpeEa0bK/c4WQoSXqFBcLylPWNspKB3c6kGzPU+rXxM4Z4g9RavLEcf+SzMVLC\nJJWgvF0uBTuim7KxPCjlhHFy5v+jlW8IFz9zV5Lyc+rjIzEr7i9vTvOguCasouVv\nU40FZf5nv/XwgzF+NiIX4je+idDqvqYtybToYc16vFhCMoaGk79WLX5YkAiYcH1L\nf++P+8+3AgMBAAECggEAZc6G1zN30UlpnaIgVXXJ3da0fptO1kpBYc7vM2/1/9uv\nQDx9Dmdern608MMFxonjDBAZHDp6DF1BupXT6KqUAZsDsKcgjz6ctXAUNA4aAMhi\no3LhTEnwb96Bmr049/grubnzHIBpPj/ixp/3k9XuxkVVbP7XqCutKKcN2XXVIZK3\npHlfxVwF/dJIOmCAhRYx4GrtnmSGPjF157TVcK+CPwfek8wTiUFlYJsRFoOIdGhT\nO3DYoiH5DX+TzzKosBDDyU6cx4lHNTkjv5/VUGMzzucYCHSWoo3Jc5nJmGW3zgC7\ndKtOp3smjKK/uu737TMosLjveNVN9dAzkUpvdxliaQKBgQDgrMfP+NW1vbroSmjC\nvcaJ8/aAomtT6BWVS/oaxb3tMZUfyaWaiw68yk/Yp3SbmDu/pukWMS0BfG+ZvYze\nOHsFvI6ikO6n2AIOnVunaWw45f1+ssr5kVGJvKFmESy1oXXXE8/HDjgb7s/48s2Y\nRNPhVxGk+o/iPYVtAms0j7w9mwKBgQC0MpxhO2kN9+/h3ap+9T+G4gVpMq2YUcBj\nAxCeE57COkHfnoXtNFDtkMsQsxk5BFlqCWUi3OzbMIkDxRkhkmJsH5uGuDCobFe6\nD0NYkJ6TS0nUYWnZvn626xR3o92QQOCHXripFFyRIH0gbhmOQUs65Ca3MBw0AE+V\nKgTrPm1mFQKBgEgQg4K8wOerdLEfdNzJ/E2xd+aosh5Wud2KYi2GMbZMChYJGtoo\nMlDx34yRocBqoveFNQxON65bWHyKpQ1+Nk+PvHx+Wl5x1a8UYBqhoPnbI2UpOhu0\ntd+lJmvTpHCZ2m9jRmkFsY+cGQ8z6igmI4QK5njxeYdKzmo5tWNFm05zAoGADJiB\nD9bcSAqtrOcWtNslvqLr5+eP9Na6EPG05qfOcBssYZouGF+QzJpTZ25tc+vW6C+R\n7zbsI4IoAah0UkFuOcqXz3nuhMdV9n58oaMyQm9/0KWihYLoTpbuDlLY+O1gBHZd\niAwRUF+p/2tSw/vSa2JpRmLJheUDqxSN1Xe+o+UCgYAWmp2qvO3mIsuEO8nb8H3O\n2WyZJy6wqSqSuigsQZzZ2lljgvEfz+JzP1Pa2YyK/Ea+lPu6uu+gjTag8zSKNuq+\nFKk7kUH71Bnouf7F3oQZRIgKK38/HuxhCU0mKJB4+eIkys6umVKcHBaMnVcMudIf\nw8hpZT63MB24fHpto0QpBg==\n-----END PRIVATE KEY-----\n",
                      "client_email": "bosh-466@data-compass.iam.gserviceaccount.com",
                      "client_id": "101964678381513587773",
                      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                      "token_uri": "https://accounts.google.com/o/oauth2/token",
                      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/bosh-466%40data-compass.iam.gserviceaccount.com"
                    }'
        default_zone: us-central1-c
      agent:
        mbus: nats://nats:nats-password@146.148.74.81:4222 # <--- Replace with the static IP
        ntp: *ntp
        blobstore:
           options:
             endpoint: http://146.148.74.81:25250 # <--- Replace with the static IP
             user: agent
             password: ev9mu1Ol0ok3wAk1Aj3

      registry:
        host: 146.148.74.81 # <--- Replace with the static IP
        username: registry
        password: ev9mu1Ol0ok3wAk1Aj3

cloud_provider:
  template:
    name: cpi
    release: bosh-google-cpi

  ssh_tunnel:
    host: 146.148.74.81 # <--- Replace with the static IP
    port: 22
    user: rajum # <--- Replace with the user corresponding to your private SSH key
    private_key: ~/.ssh/google_compute_engine # <--- Replace with the location of your google_compute_engine SSH private key

  mbus: https://mbus:mbus@146.148.74.81:6868 # <--- Replace with the static IP

  properties:
    google: *google_properties
    agent:
      mbus: https://mbus:mbus@0.0.0.0:6868
      ntp: *ntp
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
