<% num_zookeepers = 3 %>
<% num_kafka_brokers = 3 %>
<% vpc_subnet_id = "CHANGE_ME" %>
<% deployment_name = "kafka-google-gce" %>
<% zookeeper_deployment_name = "zookeeper-google-gce" %>
<% os = "ubuntu-trusty" %>
<% tld = "microbosh" %>
<% release_name = "kafka-boshrelease" %>
<% director_uuid = "CHANGE_ME" %>
---

compilation:
  cloud_properties:
    instance_type: m3.xlarge
  network: default
  reuse_compilation_vms: true
  workers: 6
name:  <%= deployment_name %>
director_uuid: <%= director_uuid %>

jobs:
- name: kafka
  networks:
  - name: default
    default: [dns, gateway]
    static_ips: null
  resource_pool: kafka
  template: kafka
  instances: <%= num_kafka_brokers %>

meta:
  environment: <%= deployment_name %>
  stemcell:
    name: bosh-google-kvm-<%= os %>
    version: latest

networks:
- name: default
  subnets:
  - range: 10.12.2.0/24
    name: default_unused
    reserved:
    - 10.12.2.2 - 10.12.2.20
    static:
    - 10.12.2.126 - 10.12.2.150
    gateway: 10.12.2.1
    dns:
    - 10.12.2.9
    cloud_properties:
      security_groups:
      - BigData-Students
      subnet: <%= vpc_subnet_id %>
      type: dynamic


releases:
- name: <%= release_name %>
  version: latest

resource_pools:
  - name: kafka
    network: default
    size: <%= num_kafka_brokers %>
    stemcell:
      name: bosh-google-kvm-<%= os %>
      version: latest
    cloud_properties:
      instance_type: t2.small
      ephemeral_disk:
        size: 10_240
        type: gp2

properties:
  zookeeper:
    servers:
      <% num_zookeepers.times do |i| %>
      <%= "- #{i}.zookeeper.default.#{zookeeper_deployment_name}.#{tld}\n" %>
      <% end %>
  kafka:
    brokers:
      <% num_kafka_brokers.times do |i| %>
      <%= "- #{i}.kafka.default.#{deployment_name}.#{tld}\n" %>
      <% end %>

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  update_watch_time: 1000-30000
